version: '3.7'

services:

    mongodb:
        image: mongo:5.0.22
        container_name: music-play-mongo-5.0.22
        volumes:
            - ./development-docker/services/mongodb/data:/data/db
        environment:
            - MONGO_DB_ROOT_USERNAME=guest
            - MONGO_DB_ROOT_PASSWORD=guest
        ports:
            - '27017:27017'

    redis:
        image: redis:5.0.5
        container_name: music-play-redis-5.0.5
        ports:
            - '6380:6380'

    rabbitmq:
        image: rabbitmq:3.11-management
        container_name: music-play-rabbitmq-3.11
        volumes:
            - ./development-docker/services/rabbitmq/etc:/etc/rabbitmq/
            - ./development-docker/services/rabbitmq/data:/var/lib/rabbitmq/
            - ./development-docker/services/rabbitmq/logs:/var/log/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - '5672:5672'
            - '15672:15672'
